### ISSUE TITLE
That model does not exist

### ISSUE THREAD

**Issue by freeblank** [Lukium/chatgpt-api-server#1]
i use the model: text-chat-davinci-002-sh-alpha-aoruigiofdj83 

openai.error.InvalidRequestError: That model does not exist

should i upgrade to ChatGPT Plus?

**Comment by Lukium** [comment]
That model might be dead now, I haven't checked in a few days as I'm working on revamped version of the API that doesn't rely on leaked models. You're welcome to hop on the Discord server to follow the development:
http://discord.gg/lukium for the main server and https://discord.gg/P74ZBySbCZ for the development server

**Comment by Lukium** [comment]
> 

Revamped code has been uploaded, try it out :)

**Comment by Lukium** [comment]
No longer relevant with current code
