### ISSUE TITLE
not remembering previous dialogue after new update

### ISSUE THREAD

**Issue by HaeImCH** [Lukium/chatgpt-api-server#2]
![image](https://media.discordapp.net/attachments/1077386848642547813/1079387168100864010/image.png)
as convasrion.json logs
can see that im requesting same conversation_id with `041229ae-66b2-4023-bd89-62b0d52d8b17`
but it did not remember previous dialogue + in web interface the conversation got wiped with last requested prompt

**Comment by Lukium** [comment]
Fixed with latest commit ad371cd0b8559cf6dcab2f607138560938845400
